// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMmb-Gh7fJeKkrLO4N82wjwP3rSLAlr0Q',
    appId: '1:284781204952:web:391b34190228274de44ead',
    messagingSenderId: '284781204952',
    projectId: 'facebook-app-54110',
    authDomain: 'facebook-app-54110.firebaseapp.com',
    storageBucket: 'facebook-app-54110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4dgsU5L0pgJizYMb6-RHHIs0Vbv_ee9U',
    appId: '1:284781204952:android:014feea2a5f69c3ce44ead',
    messagingSenderId: '284781204952',
    projectId: 'facebook-app-54110',
    storageBucket: 'facebook-app-54110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABey5OrwsC1g4fL8rDWnJ6loFWkU-Da_E',
    appId: '1:284781204952:ios:1cd7a0fde1f9e265e44ead',
    messagingSenderId: '284781204952',
    projectId: 'facebook-app-54110',
    storageBucket: 'facebook-app-54110.appspot.com',
    iosClientId: '284781204952-n4u78l575licd9njc00jont7vl6gu8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookBasicLayout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABey5OrwsC1g4fL8rDWnJ6loFWkU-Da_E',
    appId: '1:284781204952:ios:1cd7a0fde1f9e265e44ead',
    messagingSenderId: '284781204952',
    projectId: 'facebook-app-54110',
    storageBucket: 'facebook-app-54110.appspot.com',
    iosClientId: '284781204952-n4u78l575licd9njc00jont7vl6gu8qv.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookBasicLayout',
  );
}
